version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_1
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}   # Можно добавить имя базы через переменные окружения
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb_1
    ports:
      - "8080:8080"
    environment:
      # автологин админа
      NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL}
      NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      
      # Дополнительные настройки для стабильности
      NC_DISABLE_TELE: "true"
      NC_SENTRY_DSN: ""
      NC_DISABLE_ERR_LOGS: "false"
    volumes:
      - ./database/nocodb:/usr/app/data
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
